name: Deploy to Cloud Run

on:
  push:
    branches: [ "main", "21-introducing-cd" ]
  pull_request:
    branches: [ "main", "21-introducing-cd" ]

permissions:
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SVC_ACCOUNT: ${{ secrets.GCP_SVC_ACCOUNT }}
  SVC_ACCOUNT_EMAIL: ${{ secrets.GCP_SVC_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
  REGION: ${{ vars.GCP_REGION }}
  BACKEND_GCF: https://${{ vars.GCP_REGION }}-${{ secrets.GCP_PROJECT_ID }}.${{ vars.GCP_FUNCTION_URI_SUFFIX }}
  CR_UI_IMAGE_NAME: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/image-text-translator-artifacts/image-text-translator-ui:${{ github.sha }}
  BUILD_LOGS_BUCKET: gs://${{ secrets.GCP_PROJECT_ID }}-gcloud-logs
  CREDENTIALS_PATH: ${{ github.workspace }}/gcp-key.json

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check env vars
        run: |
          echo "Environment variables configured:"
          echo PROJECT_ID="$PROJECT_ID"
          echo REGION="$REGION"
          echo SVC_ACCOUNT="$SVC_ACCOUNT"
          echo SVC_ACCOUNT_EMAIL="$SVC_ACCOUNT_EMAIL"
          echo BACKEND_GCF="$BACKEND_GCF"

      - name: Write service account key file
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > $CREDENTIALS_PATH

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account $SVC_EMAIL --key-file=$CREDENTIALS_PATH
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $REGION

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Verify gcloud auth
        run: |
          gcloud auth list
          gcloud config list

      - name: Create token.json file
        run: echo "$TOKEN_JSON" > app/credentials/token.json
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}

      - name: Build Docker image and push to GCR
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/handwriting-digit-character-recognition

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy handwriting-recognition \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/handwriting-digit-character-recognition \
            --platform managed \
            --region=$REGION \
            --allow-unauthenticated

